server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: avatar
          uri: http://localhost:8082
          predicates:
            - Path=/avatars/**, 
        - id: monster
          uri: http://localhost:8083
          predicates:
            - Path=/monsters/**, 
        - id: battle
          uri: http://localhost:8084
          predicates:
            - Path=/battles/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: avatar
          uri: http://avatar:8080
          predicates:
            - Path=/avatars/**, 
        - id: monster
          uri: http://monster:8080
          predicates:
            - Path=/monsters/**, 
        - id: battle
          uri: http://battle:8080
          predicates:
            - Path=/battles/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
